/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-08 12:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formModifier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("         <link rel=\"stylesheet\" href=\"/applicationPointage/css/styleModifier.css\">\n");
      out.write("       \n");
      out.write("        <title>update employer</title>\n");
      out.write("          </head>\n");
      out.write("    <body>\n");
      out.write("    <form action=\"/applicationPointage/UpdateEmp?paraId");
      out.print(session.getAttribute("paraId") );
      out.write("\" method=\"post\">\n");
      out.write("         <div class=\"myDiv1\"> \n");
      out.write("    <img src=\"/pffNetbeans/image/signin.png\"  class=\"avatar\">\n");
      out.write("\n");
      out.write("    <br>\n");
      out.write("     <label class=\"lbl1\"  > <b>nom:</b>    </label>\n");
      out.write("     <input type=\"text\" class=\"input1\" name=\"fieldNom\" value= \"");
      out.print(session.getAttribute("nom") );
      out.write("\"><br><br>\n");
      out.write("    \n");
      out.write("      <label    class=\"lbl1\"> <b>prenom :</b>    </label>\n");
      out.write("      <input type=\"text\"  class=\"input1\" name=\"fieldPrenom\" value=\"");
      out.print(session.getAttribute("prenom") );
      out.write("\"><br><br>\n");
      out.write("       \n");
      out.write("        <label    class=\"lbl1\"> <b>email :</b>    </label>\n");
      out.write("        <input type=\"text\"  class=\"input1\" name=\"fieldEmail\" value=\"");
      out.print(session.getAttribute("email") );
      out.write("\" ><br><br>\n");
      out.write("         <label    class=\"lbl1\"> <b>mot de pass :</b>    </label>\n");
      out.write("      <input type=\"text\"  class=\"input1\" name=\"fieldMdp\" value=\"");
      out.print(session.getAttribute("mdp") );
      out.write("\"><br><br>\n");
      out.write("         <label    class=\"lbl1\"> <b>deparetement  :</b>    </label>\n");
      out.write("         <select class=\"input1\" name=\"fieldDeparetement\" >\n");
      out.write("             <option> ");
      out.print(session.getAttribute("deparetement"));
      out.write("</option>\n");
      out.write("             <option>commerce</option>\n");
      out.write("             <option>informatique</option>\n");
      out.write("             <option>logistique</option>\n");
      out.write("         </select>\n");
      out.write("        \n");
      out.write("             <button  style=\"color: black ; text-decoration: none;\" class=\"myBtn\" > modifier  </button>\n");
      out.write("             <button   class=\"myBtn1\" > <a style=\"color: black;text-decoration: none;\" href=\"/applicationPointage/jsp/pricipal.jsp\">annuler</a>  </button> \n");
      out.write("             <div>  <button  style=\"margin-top: 4%;margin-left:25%;width: 170px;border-radius: 10px;border-color: red;border-style: solid; \" class=\"myBtn1\" > <a style=\"color: black;text-decoration: none;\" href=\"/applicationPointage/removeEmp\">supprimer mon compte</a>  </button> \n");
      out.write("</div>\n");
      out.write("                 \n");
      out.write("        \n");
      out.write("      <br>\n");
      out.write("      <br>\n");
      out.write("     \n");
      out.write("      <br>\n");
      out.write("     \n");
      out.write("  </div>\n");
      out.write("      </form>\n");
      out.write("  \n");
      out.write("         \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
